openapi: 3.0.0
info:
  title: SmartGym API
  description: API documentation for the SmartGym application
  version: 0.0.1
servers:
  - url: http://localhost:8080

tags:
  - name: Ping
    description: Ping the API

  - name: Muscle Groups
    description: Muscle groups

  - name: Exercises
    description: Exercises

paths:
  /api/v1/ping:
    get:
      summary: Ping the API
      description: Ping the API to check if it is running
      tags:
        - Ping
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
              example:
                message: Pong!

  /api/v1/muscle-groups:
    get:
      summary: Get all muscle groups
      description: Get all muscle groups
      tags:
        - Muscle Groups
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MuscleGroupResponse"
              example:
                - name: DELTOIDS
                - name: BICEPS
                - name: OBLIQUES
                - name: QUADRICEPS
                - name: CHEST
                - name: FOREARM
                - name: ABS
                - name: ANKLE_FLEXORS
                - name: TRAPEZIUS
                - name: MIDDLE_BACK
                - name: LOWER_BACK
                - name: TRICEPS
                - name: BACK_OF_FOREARM
                - name: GLUTES
                - name: HAMSTRINGS
                - name: ANKLE_EXTENSORS

  /api/v1/exercises:
    get:
      summary: Get all exercises
      description: Get all exercises
      tags:
        - Exercises
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExerciseResponse"

  /api/v1/exercises/{id}:
    get:
      summary: Get an exercise by ID
      description: Get an exercise by ID
      tags:
        - Exercises
      parameters:
        - name: id
          in: path
          description: Exercise ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExerciseResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Exercise not found
                timestamp: "2021-01-01T00:00:00Z"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    MuscleGroup:
      type: string
      format: enum
      enum:
        - DELTOIDS
        - BICEPS
        - OBLIQUES
        - QUADRICEPS
        - CHEST
        - FOREARM
        - ABS
        - ANKLE_FLEXORS
        - TRAPEZIUS
        - MIDDLE_BACK
        - LOWER_BACK
        - TRICEPS
        - BACK_OF_FOREARM
        - GLUTES
        - HAMSTRINGS
        - ANKLE_EXTENSORS

    MessageResponse:
      type: object
      properties:
        message:
          type: string

    MuscleGroupResponse:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/MuscleGroup"

    ExerciseResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        muscle_groups:
          type: array
          items:
            $ref: "#/components/schemas/MuscleGroup"
        instructions:
          type: array
          items:
            type: string
        image_url:
          type: string
          format: uri
        video_url:
          type: string
          format: uri
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        name: Barbell Bench Press
        description: The barbell bench press is a classic exercise popular among all weight lifting circles. From bodybuilders to powerlifters, the bench press is a staple chest exercise in nearly every workout program.
        muscle_groups:
          - CHEST
          - TRICEPS
          - DELTOIDS
        instructions:
          - Lie down on a flat bench with a barbell in your hands, arms extended, over your chest.
          - Lower the barbell to your chest, pause, and then press it back up to the starting position.
        image_url: https://example.com/barbell-bench-press.png
        video_url: https://example.com/barbell-bench-press.mp4
